# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
#
# Note: Use CODEOWNERS file to automatically request reviews from specific users or teams

version: 2
updates:
  # Frontend dependencies (npm/pnpm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    assignees:
      - "sarvarunajvm"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
    versioning-strategy: "increase"
    groups:
      # Group minor and patch updates together
      frontend-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Separate major updates for careful review
      frontend-major:
        patterns:
          - "*"
        update-types:
          - "major"

  # Backend dependencies (Python/pip)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    assignees:
      - "sarvarunajvm"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
    versioning-strategy: "increase"
    groups:
      # Group minor and patch updates together
      backend-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      # Separate major updates for careful review
      backend-major:
        patterns:
          - "*"
        update-types:
          - "major"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    assignees:
      - "sarvarunajvm"
    labels:
      - "dependencies"
      - "ci/cd"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"
    groups:
      # Group all GitHub Actions updates
      github-actions:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"