codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 0.2%  # Only allow 0.2% drop before failing
      backend:
        target: auto
        threshold: 0.2%
        flags:
          - backend
      frontend:
        target: auto
        threshold: 0.2%
        flags:
          - frontend
    patch:
      default:
        target: 80%      # Require 80% coverage on NEW code
        threshold: 0%

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 0.2%
      - type: patch
        target: 80%

flags:
  backend:
    paths:
      - backend/
    carryforward: true
  frontend:
    paths:
      - frontend/src/
    carryforward: true
  e2e:
    paths:
      - func_tests/
    carryforward: true  # Changed to true to persist E2E results if they don't run on every commit

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false  # Update comment even if coverage didn't change (good for visibility)
  require_base: false
  require_head: true

ignore:
  # --- Backend ---
  - "backend/**/__init__.py"           # Simplified: Ignore all __init__.py files in backend
  - "backend/src/main.py"
  - "backend/alembic/"
  - "backend/scripts/"
  - "backend/src/db/migrations/"
  
  # --- Frontend ---
  - "**/*.d.ts"
  - "frontend/src/main.tsx"
  - "frontend/src/App.tsx"
  - "frontend/src/vite-env.d.ts"
  - "frontend/src/types/"
  - "frontend/src/config/"
  
  # UI Components (Presentational / Generated)
  - "frontend/src/components/ui/**"    # Shadcn/UI or library components
  - "frontend/src/lib/utils.ts"
  - "frontend/src/lib/*-variants.ts"
  
  # Specific pure components (keep if these truly have no logic)
  - "frontend/src/components/VirtualGrid/LoadingSkeleton.tsx"
  - "frontend/src/components/VirtualGrid/VirtualGridItem.tsx"
  - "frontend/src/components/Lightbox/Lightbox*.tsx"
  - "frontend/src/components/OnboardingWizard/*.tsx"

  # --- Tests & Build ---
  - "frontend/electron/"
  - "**/tests/"
  - "**/test_*"
  - "**/*test*"
  - "**/*spec*"
  - "**/__tests__/"
  - "**/__pycache__/"
  - "**/node_modules/"
  - "**/dist/"
  - "**/dist-electron/"
  - "**/build/"
  
  # --- Config Files ---
  - "**/*.config.*"
  - "**/.coveragerc"
  - "**/pytest.ini"