codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
        only_pulls: false
      backend:
        target: auto
        threshold: 1%
        informational: true
        flags:
          - backend
      frontend:
        target: auto
        threshold: 1%
        informational: true
        flags:
          - frontend
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: auto

flags:
  backend:
    paths:
      - backend/
    carryforward: true
  frontend:
    paths:
      - frontend/src/
    carryforward: true
  e2e:
    paths:
      - func_tests/
    carryforward: false
  p0-e2e:
    paths:
      - func_tests/
    carryforward: false

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  # Backend - entry points and __init__ files
  - backend/src/main.py
  - backend/src/__init__.py
  - backend/src/core/__init__.py
  - backend/src/api/__init__.py
  - backend/src/db/__init__.py
  - backend/src/db/migrations/__init__.py
  - backend/src/models/__init__.py
  - backend/src/services/__init__.py
  - backend/src/workers/__init__.py

  # Backend - test files (from .coveragerc)
  - "**/tests/*"
  - "**/test_*"
  - "**/__pycache__/*"
  - "**/site-packages/*"

  # Frontend - type definitions and entry points (from jest.config.js)
  - "**/*.d.ts"
  - frontend/src/main.tsx
  - frontend/src/App.tsx
  - frontend/src/vite-env.d.ts
  - frontend/src/setupTests.ts

  # Frontend - third-party UI components and utilities
  - frontend/src/components/ui/**
  - frontend/src/lib/*-variants.ts
  - frontend/src/lib/utils.ts
  - frontend/src/utils/logger.ts

  # Frontend - pure presentational components (no business logic)
  - frontend/src/components/VirtualGrid/LoadingSkeleton.tsx
  - frontend/src/components/VirtualGrid/VirtualGridItem.tsx
  - frontend/src/components/Lightbox/LightboxNavigation.tsx
  - frontend/src/components/Lightbox/LightboxImage.tsx
  - frontend/src/components/Lightbox/LightboxMetadata.tsx
  - frontend/src/components/OnboardingWizard/WelcomeStep.tsx
  - frontend/src/components/OnboardingWizard/CompleteStep.tsx

  # Frontend - electron and e2e
  - frontend/electron/
  - frontend/tests/e2e/
  - frontend/tests/main.test.tsx.skip
  - frontend/tests/components/ui/*.skip

  # Test files (general)
  - "**/*test*"
  - "**/*spec*"
  - "**/tests/"
  - "**/__tests__/"

  # Build and config files
  - "**/dist/"
  - "**/dist-electron/"
  - "**/build/"
  - "**/node_modules/"
  - "**/*.config.*"
  - "**/vite.config.ts"
  - "**/jest.config.js"
  - "**/pytest.ini"
  - "**/.coveragerc"
