# Codecov Configuration
# Docs: https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

# =============================================================================
# COVERAGE SETTINGS
# =============================================================================
coverage:
  precision: 2
  round: down
  range: "70...100"  # Color range: red < 70%, yellow 70-100%, green = 100%
  
  status:
    project:
      default:
        target: auto          # Must meet or exceed base branch coverage
        threshold: 0.2%       # Allow only 0.2% drop before failing
      backend:
        target: auto
        threshold: 0.2%
        flags:
          - backend
      frontend:
        target: auto
        threshold: 0.2%
        flags:
          - frontend
    patch:
      default:
        target: 80%           # Require 80% coverage on NEW code
        threshold: 0%         # Strict - no tolerance

# =============================================================================
# FLAGS - Upload-time grouping
# =============================================================================
flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 0.2%
      - type: patch
        target: 80%

flags:
  backend:
    paths:
      - backend/
    carryforward: true
  frontend:
    paths:
      - frontend/src/
    carryforward: true
  e2e:
    paths:
      - func_tests/
    carryforward: true

# =============================================================================
# COMPONENTS - Virtual filters for granular module visibility
# Docs: https://docs.codecov.com/docs/components
# =============================================================================
component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 0.5%       # Slightly more lenient for individual components
  
  individual_components:
    # --- Backend Components ---
    - component_id: backend_api
      name: "Backend: API"
      paths:
        - backend/src/api/**
    
    - component_id: backend_workers
      name: "Backend: Workers"
      paths:
        - backend/src/workers/**
    
    - component_id: backend_services
      name: "Backend: Services"
      paths:
        - backend/src/services/**
    
    - component_id: backend_models
      name: "Backend: Models"
      paths:
        - backend/src/models/**
    
    - component_id: backend_db
      name: "Backend: Database"
      paths:
        - backend/src/db/**
    
    - component_id: backend_core
      name: "Backend: Core"
      paths:
        - backend/src/core/**
    
    # --- Frontend Components ---
    - component_id: frontend_components
      name: "Frontend: Components"
      paths:
        - frontend/src/components/**
    
    - component_id: frontend_hooks
      name: "Frontend: Hooks"
      paths:
        - frontend/src/hooks/**
    
    - component_id: frontend_stores
      name: "Frontend: Stores"
      paths:
        - frontend/src/stores/**
    
    - component_id: frontend_services
      name: "Frontend: Services"
      paths:
        - frontend/src/services/**

# =============================================================================
# PR COMMENT
# Docs: https://docs.codecov.com/docs/pull-request-comments
# =============================================================================
comment:
  layout: "header, diff, flags, components, files, footer"
  behavior: default
  require_changes: false      # Update comment even if coverage didn't change
  require_base: false
  require_head: true
  show_carryforward_flags: true  # Show which flags used carried forward coverage

# =============================================================================
# IGNORED PATHS
# =============================================================================
ignore:
  # --- Backend ---
  - "backend/**/__init__.py"
  - "backend/src/main.py"
  - "backend/alembic/"
  - "backend/scripts/"
  - "backend/src/db/migrations/"
  - "backend/src/core/logging_config.py"
  
  # --- Frontend ---
  - "**/*.d.ts"
  - "frontend/src/main.tsx"
  - "frontend/src/App.tsx"
  - "frontend/src/vite-env.d.ts"
  - "frontend/src/types/"
  - "frontend/src/config/"
  - "frontend/src/utils/logger.ts"
  
  # UI Components (Presentational / Generated)
  - "frontend/src/components/ui/**"
  - "frontend/src/lib/*-variants.ts"
  
  # Pure presentational components (no business logic)
  - "frontend/src/components/Lightbox/LightboxNavigation.tsx"
  - "frontend/src/components/Lightbox/LightboxImage.tsx"
  - "frontend/src/components/Lightbox/LightboxMetadata.tsx"
  - "frontend/src/components/OnboardingWizard/WelcomeStep.tsx"
  - "frontend/src/components/OnboardingWizard/CompleteStep.tsx"

  # --- Tests & Build ---
  - "frontend/electron/"
  - "**/tests/"
  - "**/test_*"
  - "**/*test*"
  - "**/*spec*"
  - "**/__tests__/"
  - "**/__pycache__/"
  - "**/node_modules/"
  - "**/dist/"
  - "**/dist-electron/"
  - "**/build/"
  
  # --- Config Files ---
  - "**/*.config.*"
  - "**/.coveragerc"
  - "**/pytest.ini"
