name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-tam

    - name: Install Python dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Lint with ruff
      working-directory: ./backend
      run: ruff check .

    - name: Format check with black
      working-directory: ./backend
      run: black --check .

    - name: Type check with mypy
      working-directory: ./backend
      run: mypy src/

    - name: Test with pytest
      working-directory: ./backend
      run: pytest --cov=src --cov-report=xml

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        flags: backend

  frontend-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Get pnpm store directory
      working-directory: ./frontend
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      working-directory: ./frontend
      run: pnpm install --frozen-lockfile

    - name: Lint
      working-directory: ./frontend
      run: pnpm run lint

    - name: Type check
      working-directory: ./frontend
      run: pnpm run type-check

    - name: Test
      working-directory: ./frontend
      run: pnpm run test

    - name: Build
      working-directory: ./frontend
      run: pnpm run build

  shared-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Get pnpm store directory
      working-directory: ./packages/shared
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      working-directory: ./packages/shared
      run: pnpm install --frozen-lockfile

    - name: Build shared types
      working-directory: ./packages/shared
      run: pnpm run build

  integration-test:
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test, shared-test]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-tam

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: pnpm install --frozen-lockfile

    - name: Run integration tests
      run: |
        # Start backend in background
        cd backend && python -m src.main &
        sleep 10
        # Run frontend e2e tests
        cd frontend && pnpm run test:e2e