name: Full E2E Test Suite

on:
  # Run on schedule (nightly)
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC daily

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to test'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - chromium
          - firefox
          - webkit

  # Run on release branches
  push:
    branches:
      - 'release/**'

jobs:
  full-e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        shard: [1, 2, 3, 4]  # Run tests in parallel shards

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 10

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr tesseract-ocr-eng tesseract-ocr-tam

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Install frontend dependencies
      run: pnpm install --no-lockfile

    - name: Build project
      run: pnpm run build

    - name: Install Playwright browsers
      working-directory: ./tests
      run: |
        if [ "${{ github.event.inputs.browser }}" = "all" ]; then
          npx playwright install --with-deps
        else
          npx playwright install ${{ github.event.inputs.browser }} --with-deps
        fi

    - name: Run Full E2E Test Suite
      working-directory: ./tests
      env:
        CI: true
      run: |
        echo "Running full E2E test suite (shard ${{ matrix.shard }}/4)..."
        npx playwright test --shard=${{ matrix.shard }}/4

    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-shard-${{ matrix.shard }}
        path: tests/playwright-report

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-shard-${{ matrix.shard }}
        path: tests/test-results

  merge-reports:
    runs-on: ubuntu-latest
    needs: full-e2e-test
    if: always()

    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: playwright-report-shard-*
        merge-multiple: true
        path: merged-reports

    - name: Merge test reports
      run: |
        echo "Test reports from all shards have been collected"
        ls -la merged-reports/

    - name: Upload merged report
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report-full
        path: merged-reports
        retention-days: 30